# Generated by Django 5.2.7 on 2025-11-05 13:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('PACIENTE', 'Paciente'), ('MEDICO', 'Médico'), ('RECEPCIONISTA', 'Recepcionista')], default='PACIENTE', max_length=15)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('MARCADA', 'Marcada'), ('PAGA', 'Paga'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='MARCADA', max_length=10)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_dias', models.IntegerField(default=1)),
                ('cid', models.CharField(blank=True, max_length=10, verbose_name='CID')),
                ('assinatura_digital', models.CharField(max_length=100)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to='core.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixas', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('medicamentos_uso_continuo', models.TextField(blank=True, verbose_name='Medicamentos em Uso')),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='core.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('data_laudo', models.DateField(blank=True, null=True)),
                ('profissional_resp', models.CharField(blank=True, max_length=100, verbose_name='Profissional Responsável')),
                ('arquivo_resultado', models.FileField(blank=True, null=True, upload_to='exames/', verbose_name='Resultado (PDF/Imagem)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamentos', models.TextField()),
                ('posologia', models.TextField()),
                ('assinatura_digital', models.CharField(max_length=100)),
                ('qrcode', models.CharField(blank=True, max_length=255)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='core.consulta')),
            ],
        ),
    ]
