# Generated by Django 5.2.7 on 2025-11-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
