# Generated by Django 5.2.7 on 2025-11-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consulta_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='stripe_payment_intent_id',
            new_name='stripe_checkout_id',
        ),
    ]
